/* Lokales Live-Dashboard des Nerdminer V2.

   Die Seite hat absichtlich keine externen Abhaengigkeiten. Erst ein
   bewusster Klick auf einen Shop- oder Hilfe-Link verlaesst das Geraet. */

#ifndef BM24_DASHBOARD_HTML_H
#define BM24_DASHBOARD_HTML_H

#include "bm24_web_ui.h"

static const char DASHBOARD_HTML[] =
"<!doctype html><html lang=de><head><meta charset=utf-8>"
"<meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<meta name=theme-color content=\"#050607\"><title>BitMiner24 | Live</title>"
"<style>" BM24_WEB_STYLE
".hero{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(270px,.55fr);"
"gap:13px;margin-top:27px}.hero>*{min-width:0}.hero-copy{padding:28px 30px}"
".hero-copy h1{margin:0;overflow-wrap:anywhere;"
"max-width:640px;font-size:clamp(28px,5vw,48px);line-height:1.02;letter-spacing:-.035em}"
".hero-copy h1 span{color:var(--orange)}.hero-copy>p:not(.eyebrow){max-width:580px;"
"margin:14px 0 0;color:var(--muted)}.hash-panel{padding:24px;display:flex;"
"flex-direction:column;justify-content:space-between}.hash-label{color:var(--muted);"
"font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}"
".hash-value{margin:13px 0 14px;color:#fff;font-size:clamp(34px,7vw,56px);"
"font-weight:900;line-height:1;letter-spacing:-.055em}.hash-value small{color:var(--orange);"
"font-size:14px;letter-spacing:0}.meter{height:5px;overflow:hidden;border-radius:5px;"
"background:#20262b}.meter span{display:block;width:0;height:100%;border-radius:5px;"
"background:linear-gradient(90deg,var(--orange),var(--orange2));"
"box-shadow:0 0 14px var(--orange);transition:width .6s ease}"
".live-note{display:flex;justify-content:space-between;margin-top:9px;color:var(--muted);"
"font-size:10px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}"
".metric{min-height:116px;padding:17px;background:rgba(11,14,16,.92);"
"border:1px solid var(--line);border-radius:10px}.metric.hot{border-color:var(--line-hot);"
"background:linear-gradient(145deg,rgba(255,138,0,.09),rgba(11,14,16,.96))}"
".metric-key{color:var(--muted);font-size:10px;font-weight:850;letter-spacing:.12em;"
"text-transform:uppercase}.metric-value{margin-top:12px;font-size:22px;font-weight:850;"
"line-height:1.15;overflow-wrap:anywhere}.metric-sub{margin-top:5px;color:var(--muted);"
"font-size:10px}.load{padding:36px;color:var(--muted);text-align:center}"
"@media(max-width:820px){.hero{grid-template-columns:minmax(0,1fr)}.metrics{grid-template-columns:"
"repeat(2,1fr)}}@media(max-width:460px){.hero-copy,.hash-panel{padding:21px}"
".metrics{grid-template-columns:1fr 1fr}.metric{min-height:106px;padding:14px}"
".metric-value{font-size:18px}}</style></head><body>"
"<header class=\"topbar wrap\">" BM24_WEB_BRAND
"<div class=top-actions><span class=chip>NERDMINER V2</span>"
"<span id=poolState class=state>VERBINDE</span><a class=\"button ghost\" href=/setup>"
"Einstellungen</a></div></header><main class=wrap>"
"<section class=hero><div class=\"panel hero-copy\"><p class=eyebrow>Live vom Gerät</p>"
"<h1>DEIN MINER. <span>DEINE BLOCK-CHANCE.</span></h1>"
"<p>Lokale Echtzeitdaten deines Nerdminer V2. Keine Cloud, kein Konto "
"und keine Weitergabe deiner Mining-Daten.</p></div>"
"<div class=\"panel hash-panel\"><div><div class=hash-label>Aktuelle Hashrate</div>"
"<div class=hash-value><span id=hashrate>---</span> <small>kH/s</small></div></div>"
"<div><div class=meter><span id=hashMeter></span></div>"
"<div class=live-note><span>ESP32-S3</span><span id=updated>warte auf Daten</span>"
"</div></div></div></section>"
"<div class=section-head><div><p class=eyebrow>Systemstatus</p>"
"<h2>Mining auf einen Blick</h2></div><p>Aktualisierung alle 2 Sekunden</p></div>"
"<section id=metrics class=metrics><div class=load>Lade Live-Werte ...</div></section>"
"<div class=section-head><div><p class=eyebrow>BitMiner24 Ökosystem</p>"
"<h2>Mehr aus deinem Setup holen</h2></div>"
"<p>Optionale Erweiterungen für dein Solo-Mining-Setup</p></div>"
"<section class=commerce>"
"<a class=\"offer featured\" target=_blank rel=noopener href=\"" BM24_SHOP_NERDNOS "\">"
"<span class=offer-tag>Mehr Hashrate</span><h3>NerdNOS</h3>"
"<p>Der nächste Schritt vom lautlosen Lern-Miner zum kompakten ASIC-Solo-Miner.</p>"
"<span class=offer-cta>NerdNOS ansehen <span>&rarr;</span></span></a>"
"<a class=offer target=_blank rel=noopener href=\"" BM24_SHOP_V2 "\">"
"<span class=offer-tag>Parallel minen</span><h3>Zweiter Nerdminer V2</h3>"
"<p>Zwei unabhängige Geräte können parallel auf dieselbe Bitcoin-Adresse minen.</p>"
"<span class=offer-cta>V2 entdecken <span>&rarr;</span></span></a>"
"<a class=offer target=_blank rel=noopener href=\"" BM24_GUIDES "\">"
"<span class=offer-tag>Wissen &amp; Hilfe</span><h3>Guides von BitMiner24</h3>"
"<p>Einrichtung, Technik und ehrliche Einordnung rund um Solo Mining.</p>"
"<span class=offer-cta>Guides öffnen <span>&rarr;</span></span></a>"
"</section></main><footer class=\"footer wrap\"><span>BitMiner24 Firmware 2.0"
" &middot; lokale Geräteseite</span><span><a target=_blank rel=noopener href=\""
BM24_SHOP_HARDWARE "\">Hardware</a> &middot; <a target=_blank rel=noopener href=\""
BM24_SUPPORT "\">Support</a></span></footer>"
"<script>\n"
"function card(k,v,sub,hot){return '<article class=\"metric'+(hot?' hot':'')+'\">'+"
"'<div class=metric-key>'+k+'</div><div class=metric-value>'+v+'</div>'+"
"'<div class=metric-sub>'+sub+'</div></article>';}\n"
"function tick(){\n"
" fetch('/status',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error();"
"return r.json()}).then(function(s){\n"
"  document.getElementById('hashrate').textContent=Number(s.khs).toFixed(1);\n"
"  document.getElementById('hashMeter').style.width=Math.min(100,Number(s.khs)/4)+'%';\n"
"  document.getElementById('updated').textContent='Update '+"
"new Date().toLocaleTimeString('de-DE');\n"
"  var p=document.getElementById('poolState');p.className='state '+(s.pool?'ok':'bad');"
"p.textContent=s.pool?'POOL ONLINE':'POOL GETRENNT';\n"
"  document.getElementById('metrics').innerHTML="
"card('Temperatur',Number(s.temp).toFixed(1)+' &deg;C','Chiptemperatur',false)+"
"card('Shares',s.accepted+' / '+s.submitted,'Akzeptiert / gesendet',false)+"
"card('Block gefunden',s.blocks_found,'Bestätigte Netzwerkblöcke',true)+"
"card('Beste Difficulty',Number(s.best).toPrecision(6),'Persönliche Bestmarke',false)+"
"card('Pool',s.pool?'Online':'Getrennt','Stratum-Verbindung',false)+"
"card('Laufzeit',s.uptime,'Dauerhaft gespeichert',false)+"
"card('Pool-Worker',s.workers,'Unter deiner Adresse',false)+"
"card('Firmware',s.version,'BitMiner24 Software',false);\n"
" }).catch(function(){var p=document.getElementById('poolState');p.className='state bad';"
"p.textContent='GERÄT OFFLINE';});\n"
"}\n"
"tick();setInterval(tick,2000);\n"
"</script></body></html>";

#endif /* BM24_DASHBOARD_HTML_H */
